apiVersion: v1
kind: Service
metadata:
  name: {{ include "axiograph.fullname" . }}-db-headless
  labels:
    {{- include "axiograph.labels" . | nindent 4 }}
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: {{ include "axiograph.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
