[package]
name = "axiograph-ingest-iges"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "IGES file parser for Axiograph"

[dependencies]
axiograph-dsl = { path = "../axiograph-dsl" }
anyhow.workspace = true
regex.workspace = true

